%% =============================================================================
%% markdownviewer_web_pro — State Machine Facts
%% Generated by sm_init_project. Edit with sm_add_fact / sm_remove_fact.
%% =============================================================================

%% Add your state machines below using sm_init_machine, then populate with
%% sm_add_fact. Run sm_check_invariants or sm_report to see findings.
%%
%% Example:
%%   valid_state(markdownviewer_web_pro_main, idle).
%%   initial(markdownviewer_web_pro_main, idle).
%%   transition(markdownviewer_web_pro_main, idle, running).
%%   terminal(markdownviewer_web_pro_main, done).
%% =============================================================================
%% State Machine: fullscreen_mode
%% Generated by sm_init_machine
%% =============================================================================

:- discontiguous valid_state/2, transition/3, initial/2, terminal/2,
                  error_transition/3, requires_cleanup/2, cleanup_on_transition/3,
                  flag/2, mutually_exclusive/2, guarded/3,
                  source_file/3, description/3.

valid_state(fullscreen_mode, dual_pane).
valid_state(fullscreen_mode, fullscreen_preview).
valid_state(fullscreen_mode, fullscreen_edit).

initial(fullscreen_mode, dual_pane).

%% Normal transitions
%% transition(fullscreen_mode, from_state, to_state).

%% Error transitions
%% error_transition(fullscreen_mode, from_state, error_state).

%% Cleanup declarations
%% requires_cleanup(fullscreen_mode, state).
%% cleanup_on_transition(fullscreen_mode, from_state, to_state).

%% Flags and guards
%% flag(fullscreen_mode, flag_name).
%% mutually_exclusive(flag_a, flag_b).
%% guarded(fullscreen_mode, flag_a, flag_b).

%% Async / concurrency / resource predicates
%% awaits(fullscreen_mode, state, resource).
%% timeout_handler(fullscreen_mode, state, resource).
%% race_risk(fullscreen_mode, state_a, state_b).
%% acquires(fullscreen_mode, state, resource).
%% releases(fullscreen_mode, state, resource).
%% reads(fullscreen_mode, state, variable).
%% writes(fullscreen_mode, state, variable).

%% Source mappings
source_file(fullscreen_mode, dual_pane, './js/core.js').
source_file(fullscreen_mode, fullscreen_preview, './js/core.js').
source_file(fullscreen_mode, fullscreen_edit, './js/core.js').

%% Design checklist
%% 1) Which states can fail? Add error_transition for each non-terminal state.
%% 2) Which states hold timers/file handles/locks? Add requires_cleanup and cleanup_on_transition.
%% 3) Are there explicit exit points (process.exit/throw/return)? Model as terminal or error_transition.
%% 4) If async wait is involved, define timeout/error path so waits cannot hang silently.
%% 5) If a state reads async data, define writes() path before reads() and guard races.

%% =============================================================================
%% State Machine: compact_expand_mode
%% Generated by sm_init_machine
%% =============================================================================

:- discontiguous valid_state/2, transition/3, initial/2, terminal/2,
                  error_transition/3, requires_cleanup/2, cleanup_on_transition/3,
                  flag/2, mutually_exclusive/2, guarded/3,
                  source_file/3, description/3.

valid_state(compact_expand_mode, expanded).
valid_state(compact_expand_mode, compact).

initial(compact_expand_mode, expanded).

%% Normal transitions
%% transition(compact_expand_mode, from_state, to_state).

%% Error transitions
%% error_transition(compact_expand_mode, from_state, error_state).

%% Cleanup declarations
%% requires_cleanup(compact_expand_mode, state).
%% cleanup_on_transition(compact_expand_mode, from_state, to_state).

%% Flags and guards
%% flag(compact_expand_mode, flag_name).
%% mutually_exclusive(flag_a, flag_b).
%% guarded(compact_expand_mode, flag_a, flag_b).

%% Async / concurrency / resource predicates
%% awaits(compact_expand_mode, state, resource).
%% timeout_handler(compact_expand_mode, state, resource).
%% race_risk(compact_expand_mode, state_a, state_b).
%% acquires(compact_expand_mode, state, resource).
%% releases(compact_expand_mode, state, resource).
%% reads(compact_expand_mode, state, variable).
%% writes(compact_expand_mode, state, variable).

%% Source mappings
source_file(compact_expand_mode, expanded, './js/core.js').
source_file(compact_expand_mode, compact, './js/core.js').

%% Design checklist
%% 1) Which states can fail? Add error_transition for each non-terminal state.
%% 2) Which states hold timers/file handles/locks? Add requires_cleanup and cleanup_on_transition.
%% 3) Are there explicit exit points (process.exit/throw/return)? Model as terminal or error_transition.
%% 4) If async wait is involved, define timeout/error path so waits cannot hang silently.
%% 5) If a state reads async data, define writes() path before reads() and guard races.

transition(fullscreen_mode, dual_pane, fullscreen_preview).
transition(fullscreen_mode, fullscreen_preview, dual_pane).
transition(fullscreen_mode, fullscreen_edit, dual_pane).
transition(fullscreen_mode, fullscreen_preview, fullscreen_edit).
transition(fullscreen_mode, fullscreen_edit, fullscreen_preview).
transition(compact_expand_mode, expanded, compact).
transition(compact_expand_mode, compact, expanded).
valid_state(fullscreen_mode, closed).
terminal(fullscreen_mode, closed).
valid_state(fullscreen_mode, error).
terminal(fullscreen_mode, error).
valid_state(compact_expand_mode, closed).
terminal(compact_expand_mode, closed).
valid_state(compact_expand_mode, error).
terminal(compact_expand_mode, error).
transition(fullscreen_mode, dual_pane, closed).
transition(fullscreen_mode, fullscreen_preview, closed).
transition(fullscreen_mode, fullscreen_edit, closed).
error_transition(fullscreen_mode, dual_pane, error).
error_transition(fullscreen_mode, fullscreen_preview, error).
error_transition(fullscreen_mode, fullscreen_edit, error).
transition(compact_expand_mode, expanded, closed).
transition(compact_expand_mode, compact, closed).
error_transition(compact_expand_mode, expanded, error).
error_transition(compact_expand_mode, compact, error).
%% =============================================================================
%% State Machine: open_file_flow
%% Generated by sm_init_machine
%% =============================================================================

:- discontiguous valid_state/2, transition/3, initial/2, terminal/2,
                  error_transition/3, requires_cleanup/2, cleanup_on_transition/3,
                  flag/2, mutually_exclusive/2, guarded/3,
                  source_file/3, description/3.

valid_state(open_file_flow, start).
valid_state(open_file_flow, check_backend).
valid_state(open_file_flow, open_indexeddb_browser).
valid_state(open_file_flow, open_indexeddb_failed).
valid_state(open_file_flow, open_disk_filepicker).
valid_state(open_file_flow, missing_file_input).
valid_state(open_file_flow, done).
valid_state(open_file_flow, error).

initial(open_file_flow, start).
terminal(open_file_flow, done).
terminal(open_file_flow, error).

%% Normal transitions
%% transition(open_file_flow, from_state, to_state).

%% Error transitions
%% error_transition(open_file_flow, from_state, error_state).

%% Cleanup declarations
%% requires_cleanup(open_file_flow, state).
%% cleanup_on_transition(open_file_flow, from_state, to_state).

%% Flags and guards
%% flag(open_file_flow, flag_name).
%% mutually_exclusive(flag_a, flag_b).
%% guarded(open_file_flow, flag_a, flag_b).

%% Async / concurrency / resource predicates
%% awaits(open_file_flow, state, resource).
%% timeout_handler(open_file_flow, state, resource).
%% race_risk(open_file_flow, state_a, state_b).
%% acquires(open_file_flow, state, resource).
%% releases(open_file_flow, state, resource).
%% reads(open_file_flow, state, variable).
%% writes(open_file_flow, state, variable).

%% Source mappings
source_file(open_file_flow, start, './js/file-operations.js').
source_file(open_file_flow, check_backend, './js/file-operations.js').
source_file(open_file_flow, open_indexeddb_browser, './js/file-operations.js').
source_file(open_file_flow, open_indexeddb_failed, './js/file-operations.js').
source_file(open_file_flow, open_disk_filepicker, './js/file-operations.js').
source_file(open_file_flow, missing_file_input, './js/file-operations.js').
source_file(open_file_flow, done, './js/file-operations.js').
source_file(open_file_flow, error, './js/file-operations.js').

%% Design checklist
%% 1) Which states can fail? Add error_transition for each non-terminal state.
%% 2) Which states hold timers/file handles/locks? Add requires_cleanup and cleanup_on_transition.
%% 3) Are there explicit exit points (process.exit/throw/return)? Model as terminal or error_transition.
%% 4) If async wait is involved, define timeout/error path so waits cannot hang silently.
%% 5) If a state reads async data, define writes() path before reads() and guard races.

%% =============================================================================
%% State Machine: new_file_flow
%% Generated by sm_init_machine
%% =============================================================================

:- discontiguous valid_state/2, transition/3, initial/2, terminal/2,
                  error_transition/3, requires_cleanup/2, cleanup_on_transition/3,
                  flag/2, mutually_exclusive/2, guarded/3,
                  source_file/3, description/3.

valid_state(new_file_flow, start).
valid_state(new_file_flow, prompt_user).
valid_state(new_file_flow, cancel).
valid_state(new_file_flow, pre_save_browser).
valid_state(new_file_flow, save_failed).
valid_state(new_file_flow, download_file).
valid_state(new_file_flow, delete_from_indexeddb).
valid_state(new_file_flow, discard).
valid_state(new_file_flow, clear_editor).
valid_state(new_file_flow, update_ui).
valid_state(new_file_flow, replace_buffer).
valid_state(new_file_flow, focus_editor).
valid_state(new_file_flow, notify_success).
valid_state(new_file_flow, reset_scroll).
valid_state(new_file_flow, done).
valid_state(new_file_flow, error).

initial(new_file_flow, start).
terminal(new_file_flow, cancel).
terminal(new_file_flow, save_failed).
terminal(new_file_flow, done).
terminal(new_file_flow, error).

%% Normal transitions
%% transition(new_file_flow, from_state, to_state).

%% Error transitions
%% error_transition(new_file_flow, from_state, error_state).

%% Cleanup declarations
%% requires_cleanup(new_file_flow, state).
%% cleanup_on_transition(new_file_flow, from_state, to_state).

%% Flags and guards
%% flag(new_file_flow, flag_name).
%% mutually_exclusive(flag_a, flag_b).
%% guarded(new_file_flow, flag_a, flag_b).

%% Async / concurrency / resource predicates
%% awaits(new_file_flow, state, resource).
%% timeout_handler(new_file_flow, state, resource).
%% race_risk(new_file_flow, state_a, state_b).
%% acquires(new_file_flow, state, resource).
%% releases(new_file_flow, state, resource).
%% reads(new_file_flow, state, variable).
%% writes(new_file_flow, state, variable).

%% Source mappings
source_file(new_file_flow, start, './js/file-operations.js').
source_file(new_file_flow, prompt_user, './js/file-operations.js').
source_file(new_file_flow, cancel, './js/file-operations.js').
source_file(new_file_flow, pre_save_browser, './js/file-operations.js').
source_file(new_file_flow, save_failed, './js/file-operations.js').
source_file(new_file_flow, download_file, './js/file-operations.js').
source_file(new_file_flow, delete_from_indexeddb, './js/file-operations.js').
source_file(new_file_flow, discard, './js/file-operations.js').
source_file(new_file_flow, clear_editor, './js/file-operations.js').
source_file(new_file_flow, update_ui, './js/file-operations.js').
source_file(new_file_flow, replace_buffer, './js/file-operations.js').
source_file(new_file_flow, focus_editor, './js/file-operations.js').
source_file(new_file_flow, notify_success, './js/file-operations.js').
source_file(new_file_flow, reset_scroll, './js/file-operations.js').
source_file(new_file_flow, done, './js/file-operations.js').
source_file(new_file_flow, error, './js/file-operations.js').

%% Design checklist
%% 1) Which states can fail? Add error_transition for each non-terminal state.
%% 2) Which states hold timers/file handles/locks? Add requires_cleanup and cleanup_on_transition.
%% 3) Are there explicit exit points (process.exit/throw/return)? Model as terminal or error_transition.
%% 4) If async wait is involved, define timeout/error path so waits cannot hang silently.
%% 5) If a state reads async data, define writes() path before reads() and guard races.

%% =============================================================================
%% State Machine: word_import_flow
%% Generated by sm_init_machine
%% =============================================================================

:- discontiguous valid_state/2, transition/3, initial/2, terminal/2,
                  error_transition/3, requires_cleanup/2, cleanup_on_transition/3,
                  flag/2, mutually_exclusive/2, guarded/3,
                  source_file/3, description/3.

valid_state(word_import_flow, start).
valid_state(word_import_flow, check_file_selected).
valid_state(word_import_flow, check_mammoth).
valid_state(word_import_flow, mammoth_missing).
valid_state(word_import_flow, retry_wait).
valid_state(word_import_flow, process_word_file).
valid_state(word_import_flow, read_arraybuffer).
valid_state(word_import_flow, convert_to_html).
valid_state(word_import_flow, convert_to_markdown).
valid_state(word_import_flow, apply_editor_updates).
valid_state(word_import_flow, done_success).
valid_state(word_import_flow, done_error).

initial(word_import_flow, start).
terminal(word_import_flow, done_success).
terminal(word_import_flow, done_error).

%% Normal transitions
%% transition(word_import_flow, from_state, to_state).

%% Error transitions
%% error_transition(word_import_flow, from_state, error_state).

%% Cleanup declarations
%% requires_cleanup(word_import_flow, state).
%% cleanup_on_transition(word_import_flow, from_state, to_state).

%% Flags and guards
%% flag(word_import_flow, flag_name).
%% mutually_exclusive(flag_a, flag_b).
%% guarded(word_import_flow, flag_a, flag_b).

%% Async / concurrency / resource predicates
%% awaits(word_import_flow, state, resource).
%% timeout_handler(word_import_flow, state, resource).
%% race_risk(word_import_flow, state_a, state_b).
%% acquires(word_import_flow, state, resource).
%% releases(word_import_flow, state, resource).
%% reads(word_import_flow, state, variable).
%% writes(word_import_flow, state, variable).

%% Source mappings
source_file(word_import_flow, start, './js/file-operations.js').
source_file(word_import_flow, check_file_selected, './js/file-operations.js').
source_file(word_import_flow, check_mammoth, './js/file-operations.js').
source_file(word_import_flow, mammoth_missing, './js/file-operations.js').
source_file(word_import_flow, retry_wait, './js/file-operations.js').
source_file(word_import_flow, process_word_file, './js/file-operations.js').
source_file(word_import_flow, read_arraybuffer, './js/file-operations.js').
source_file(word_import_flow, convert_to_html, './js/file-operations.js').
source_file(word_import_flow, convert_to_markdown, './js/file-operations.js').
source_file(word_import_flow, apply_editor_updates, './js/file-operations.js').
source_file(word_import_flow, done_success, './js/file-operations.js').
source_file(word_import_flow, done_error, './js/file-operations.js').

%% Design checklist
%% 1) Which states can fail? Add error_transition for each non-terminal state.
%% 2) Which states hold timers/file handles/locks? Add requires_cleanup and cleanup_on_transition.
%% 3) Are there explicit exit points (process.exit/throw/return)? Model as terminal or error_transition.
%% 4) If async wait is involved, define timeout/error path so waits cannot hang silently.
%% 5) If a state reads async data, define writes() path before reads() and guard races.

transition(open_file_flow, start, check_backend).
transition(open_file_flow, check_backend, open_indexeddb_browser).
transition(open_file_flow, check_backend, open_disk_filepicker).
transition(open_file_flow, open_indexeddb_browser, done).
error_transition(open_file_flow, open_indexeddb_browser, open_indexeddb_failed).
transition(open_file_flow, open_indexeddb_failed, done).
transition(open_file_flow, open_disk_filepicker, done).
transition(open_file_flow, open_disk_filepicker, missing_file_input).
transition(open_file_flow, missing_file_input, done).
error_transition(open_file_flow, start, error).
error_transition(open_file_flow, check_backend, error).
error_transition(open_file_flow, open_indexeddb_failed, error).
error_transition(open_file_flow, open_disk_filepicker, error).
error_transition(open_file_flow, missing_file_input, error).
transition(new_file_flow, start, prompt_user).
transition(new_file_flow, prompt_user, cancel).
transition(new_file_flow, prompt_user, pre_save_browser).
transition(new_file_flow, pre_save_browser, save_failed).
transition(new_file_flow, pre_save_browser, clear_editor).
transition(new_file_flow, prompt_user, download_file).
transition(new_file_flow, download_file, clear_editor).
transition(new_file_flow, prompt_user, delete_from_indexeddb).
transition(new_file_flow, delete_from_indexeddb, clear_editor).
transition(new_file_flow, prompt_user, discard).
transition(new_file_flow, discard, clear_editor).
transition(new_file_flow, clear_editor, update_ui).
transition(new_file_flow, update_ui, replace_buffer).
transition(new_file_flow, replace_buffer, focus_editor).
transition(new_file_flow, focus_editor, notify_success).
transition(new_file_flow, notify_success, reset_scroll).
transition(new_file_flow, reset_scroll, done).
error_transition(new_file_flow, pre_save_browser, error).
error_transition(new_file_flow, download_file, error).
error_transition(new_file_flow, delete_from_indexeddb, error).
error_transition(new_file_flow, clear_editor, error).
error_transition(new_file_flow, update_ui, error).
error_transition(new_file_flow, replace_buffer, error).
error_transition(new_file_flow, focus_editor, error).
error_transition(new_file_flow, notify_success, error).
error_transition(new_file_flow, reset_scroll, error).
transition(word_import_flow, start, check_file_selected).
transition(word_import_flow, check_file_selected, check_mammoth).
transition(word_import_flow, check_file_selected, done_error).
transition(word_import_flow, check_mammoth, process_word_file).
transition(word_import_flow, check_mammoth, mammoth_missing).
transition(word_import_flow, mammoth_missing, retry_wait).
transition(word_import_flow, retry_wait, process_word_file).
transition(word_import_flow, retry_wait, done_error).
transition(word_import_flow, process_word_file, read_arraybuffer).
transition(word_import_flow, read_arraybuffer, convert_to_html).
transition(word_import_flow, convert_to_html, convert_to_markdown).
transition(word_import_flow, convert_to_markdown, apply_editor_updates).
transition(word_import_flow, apply_editor_updates, done_success).
error_transition(word_import_flow, process_word_file, done_error).
error_transition(word_import_flow, read_arraybuffer, done_error).
error_transition(word_import_flow, convert_to_html, done_error).
error_transition(word_import_flow, convert_to_markdown, done_error).
error_transition(word_import_flow, apply_editor_updates, done_error).
error_transition(new_file_flow, start, error).
error_transition(new_file_flow, prompt_user, error).
error_transition(new_file_flow, discard, error).
error_transition(word_import_flow, start, done_error).
error_transition(word_import_flow, check_file_selected, done_error).
error_transition(word_import_flow, check_mammoth, done_error).
error_transition(word_import_flow, mammoth_missing, done_error).
error_transition(word_import_flow, retry_wait, done_error).
%% =============================================================================
%% State Machine: drag_drop_flow
%% Generated by sm_init_machine
%% =============================================================================

:- discontiguous valid_state/2, transition/3, initial/2, terminal/2,
                  error_transition/3, requires_cleanup/2, cleanup_on_transition/3,
                  flag/2, mutually_exclusive/2, guarded/3,
                  source_file/3, description/3.

valid_state(drag_drop_flow, idle).
valid_state(drag_drop_flow, dragging_over).
valid_state(drag_drop_flow, processing).
valid_state(drag_drop_flow, loaded).
valid_state(drag_drop_flow, error).

initial(drag_drop_flow, idle).
terminal(drag_drop_flow, loaded).
terminal(drag_drop_flow, error).

%% Normal transitions
%% transition(drag_drop_flow, from_state, to_state).

%% Error transitions
%% error_transition(drag_drop_flow, from_state, error_state).

%% Cleanup declarations
%% requires_cleanup(drag_drop_flow, state).
%% cleanup_on_transition(drag_drop_flow, from_state, to_state).

%% Flags and guards
%% flag(drag_drop_flow, flag_name).
%% mutually_exclusive(flag_a, flag_b).
%% guarded(drag_drop_flow, flag_a, flag_b).

%% Async / concurrency / resource predicates
%% awaits(drag_drop_flow, state, resource).
%% timeout_handler(drag_drop_flow, state, resource).
%% race_risk(drag_drop_flow, state_a, state_b).
%% acquires(drag_drop_flow, state, resource).
%% releases(drag_drop_flow, state, resource).
%% reads(drag_drop_flow, state, variable).
%% writes(drag_drop_flow, state, variable).

%% Source mappings
source_file(drag_drop_flow, idle, './js/drag-drop.js').
source_file(drag_drop_flow, dragging_over, './js/drag-drop.js').
source_file(drag_drop_flow, processing, './js/drag-drop.js').
source_file(drag_drop_flow, loaded, './js/drag-drop.js').
source_file(drag_drop_flow, error, './js/drag-drop.js').

%% Design checklist
%% 1) Which states can fail? Add error_transition for each non-terminal state.
%% 2) Which states hold timers/file handles/locks? Add requires_cleanup and cleanup_on_transition.
%% 3) Are there explicit exit points (process.exit/throw/return)? Model as terminal or error_transition.
%% 4) If async wait is involved, define timeout/error path so waits cannot hang silently.
%% 5) If a state reads async data, define writes() path before reads() and guard races.

transition(drag_drop_flow, idle, dragging_over).
transition(drag_drop_flow, dragging_over, idle).
transition(drag_drop_flow, dragging_over, processing).
transition(drag_drop_flow, processing, loaded).
error_transition(drag_drop_flow, dragging_over, error).
error_transition(drag_drop_flow, processing, error).
valid_state(drag_drop_flow, dragging_over_editor).
valid_state(drag_drop_flow, dragging_over_preview).
transition(drag_drop_flow, idle, dragging_over_editor).
transition(drag_drop_flow, idle, dragging_over_preview).
transition(drag_drop_flow, dragging_over_editor, idle).
transition(drag_drop_flow, dragging_over_preview, idle).
transition(drag_drop_flow, dragging_over_editor, processing).
transition(drag_drop_flow, dragging_over_preview, processing).
%% =============================================================================
%% State Machine: storage_flow
%% Generated by sm_init_machine
%% =============================================================================

:- discontiguous valid_state/2, transition/3, initial/2, terminal/2,
                  error_transition/3, requires_cleanup/2, cleanup_on_transition/3,
                  flag/2, mutually_exclusive/2, guarded/3,
                  source_file/3, description/3.

valid_state(storage_flow, idle).
valid_state(storage_flow, connecting).
valid_state(storage_flow, connected).
valid_state(storage_flow, reading).
valid_state(storage_flow, writing).
valid_state(storage_flow, error).
valid_state(storage_flow, quota_exceeded).
valid_state(storage_flow, corrupted).
valid_state(storage_flow, cleanup).

initial(storage_flow, idle).
terminal(storage_flow, connected).
terminal(storage_flow, error).
terminal(storage_flow, quota_exceeded).
terminal(storage_flow, corrupted).

%% Normal transitions
%% transition(storage_flow, from_state, to_state).

%% Error transitions
%% error_transition(storage_flow, from_state, error_state).

%% Cleanup declarations
%% requires_cleanup(storage_flow, state).
%% cleanup_on_transition(storage_flow, from_state, to_state).

%% Flags and guards
%% flag(storage_flow, flag_name).
%% mutually_exclusive(flag_a, flag_b).
%% guarded(storage_flow, flag_a, flag_b).

%% Async / concurrency / resource predicates
%% awaits(storage_flow, state, resource).
%% timeout_handler(storage_flow, state, resource).
%% race_risk(storage_flow, state_a, state_b).
%% acquires(storage_flow, state, resource).
%% releases(storage_flow, state, resource).
%% reads(storage_flow, state, variable).
%% writes(storage_flow, state, variable).

%% Source mappings
source_file(storage_flow, idle, './js/storage-manager.js').
source_file(storage_flow, connecting, './js/storage-manager.js').
source_file(storage_flow, connected, './js/storage-manager.js').
source_file(storage_flow, reading, './js/storage-manager.js').
source_file(storage_flow, writing, './js/storage-manager.js').
source_file(storage_flow, error, './js/storage-manager.js').
source_file(storage_flow, quota_exceeded, './js/storage-manager.js').
source_file(storage_flow, corrupted, './js/storage-manager.js').
source_file(storage_flow, cleanup, './js/storage-manager.js').

%% Design checklist
%% 1) Which states can fail? Add error_transition for each non-terminal state.
%% 2) Which states hold timers/file handles/locks? Add requires_cleanup and cleanup_on_transition.
%% 3) Are there explicit exit points (process.exit/throw/return)? Model as terminal or error_transition.
%% 4) If async wait is involved, define timeout/error path so waits cannot hang silently.
%% 5) If a state reads async data, define writes() path before reads() and guard races.

%% =============================================================================
%% State Machine: indexeddb_flow
%% Generated by sm_init_machine
%% =============================================================================

:- discontiguous valid_state/2, transition/3, initial/2, terminal/2,
                  error_transition/3, requires_cleanup/2, cleanup_on_transition/3,
                  flag/2, mutually_exclusive/2, guarded/3,
                  source_file/3, description/3.

valid_state(indexeddb_flow, idle).
valid_state(indexeddb_flow, opening_db).
valid_state(indexeddb_flow, db_open).
valid_state(indexeddb_flow, creating_stores).
valid_state(indexeddb_flow, transaction_start).
valid_state(indexeddb_flow, reading).
valid_state(indexeddb_flow, writing).
valid_state(indexeddb_flow, committing).
valid_state(indexeddb_flow, error).
valid_state(indexeddb_flow, db_corrupted).
valid_state(indexeddb_flow, quota_exceeded).
valid_state(indexeddb_flow, cleanup).

initial(indexeddb_flow, idle).
terminal(indexeddb_flow, db_open).
terminal(indexeddb_flow, error).
terminal(indexeddb_flow, db_corrupted).
terminal(indexeddb_flow, quota_exceeded).

%% Normal transitions
%% transition(indexeddb_flow, from_state, to_state).

%% Error transitions
%% error_transition(indexeddb_flow, from_state, error_state).

%% Cleanup declarations
%% requires_cleanup(indexeddb_flow, state).
%% cleanup_on_transition(indexeddb_flow, from_state, to_state).

%% Flags and guards
%% flag(indexeddb_flow, flag_name).
%% mutually_exclusive(flag_a, flag_b).
%% guarded(indexeddb_flow, flag_a, flag_b).

%% Async / concurrency / resource predicates
%% awaits(indexeddb_flow, state, resource).
%% timeout_handler(indexeddb_flow, state, resource).
%% race_risk(indexeddb_flow, state_a, state_b).
%% acquires(indexeddb_flow, state, resource).
%% releases(indexeddb_flow, state, resource).
%% reads(indexeddb_flow, state, variable).
%% writes(indexeddb_flow, state, variable).

%% Source mappings
source_file(indexeddb_flow, idle, './js/indexeddb-manager.js').
source_file(indexeddb_flow, opening_db, './js/indexeddb-manager.js').
source_file(indexeddb_flow, db_open, './js/indexeddb-manager.js').
source_file(indexeddb_flow, creating_stores, './js/indexeddb-manager.js').
source_file(indexeddb_flow, transaction_start, './js/indexeddb-manager.js').
source_file(indexeddb_flow, reading, './js/indexeddb-manager.js').
source_file(indexeddb_flow, writing, './js/indexeddb-manager.js').
source_file(indexeddb_flow, committing, './js/indexeddb-manager.js').
source_file(indexeddb_flow, error, './js/indexeddb-manager.js').
source_file(indexeddb_flow, db_corrupted, './js/indexeddb-manager.js').
source_file(indexeddb_flow, quota_exceeded, './js/indexeddb-manager.js').
source_file(indexeddb_flow, cleanup, './js/indexeddb-manager.js').

%% Design checklist
%% 1) Which states can fail? Add error_transition for each non-terminal state.
%% 2) Which states hold timers/file handles/locks? Add requires_cleanup and cleanup_on_transition.
%% 3) Are there explicit exit points (process.exit/throw/return)? Model as terminal or error_transition.
%% 4) If async wait is involved, define timeout/error path so waits cannot hang silently.
%% 5) If a state reads async data, define writes() path before reads() and guard races.

transition(storage_flow, idle, connecting).
transition(storage_flow, connecting, connected).
transition(storage_flow, connected, reading).
transition(storage_flow, connected, writing).
transition(storage_flow, reading, connected).
transition(storage_flow, writing, connected).
error_transition(storage_flow, connecting, error).
error_transition(storage_flow, reading, error).
error_transition(storage_flow, writing, error).
error_transition(storage_flow, connected, quota_exceeded).
error_transition(storage_flow, reading, corrupted).
error_transition(storage_flow, writing, corrupted).
transition(storage_flow, error, cleanup).
transition(storage_flow, quota_exceeded, cleanup).
transition(storage_flow, corrupted, cleanup).
transition(storage_flow, cleanup, idle).
transition(indexeddb_flow, idle, opening_db).
transition(indexeddb_flow, opening_db, creating_stores).
transition(indexeddb_flow, creating_stores, db_open).
transition(indexeddb_flow, db_open, transaction_start).
transition(indexeddb_flow, transaction_start, reading).
transition(indexeddb_flow, transaction_start, writing).
transition(indexeddb_flow, reading, committing).
transition(indexeddb_flow, writing, committing).
transition(indexeddb_flow, committing, db_open).
error_transition(indexeddb_flow, opening_db, error).
error_transition(indexeddb_flow, creating_stores, error).
error_transition(indexeddb_flow, reading, error).
error_transition(indexeddb_flow, writing, error).
error_transition(indexeddb_flow, committing, error).
error_transition(indexeddb_flow, db_open, quota_exceeded).
error_transition(indexeddb_flow, transaction_start, db_corrupted).
error_transition(indexeddb_flow, reading, db_corrupted).
error_transition(indexeddb_flow, writing, db_corrupted).
transition(indexeddb_flow, error, cleanup).
transition(indexeddb_flow, quota_exceeded, cleanup).
transition(indexeddb_flow, db_corrupted, cleanup).
transition(indexeddb_flow, cleanup, idle).
